---
- name: Add epel release
  sudo: yes
  yum: name=http://rpms.famillecollet.com/enterprise/remi-release-7.rpm state=present

- name: Add PHP 7 embed
  sudo: yes
  yum: enablerepo=remi name=php70-php-embedded state=present

- name: Install PHP 7
  sudo: yes
  yum: name=php70 state=present

- name: Install PHP 7 packages
  sudo: yes
  yum: pkg={{ item }} state=latest
  with_items: php.packages
  when: php.packages is defined

- name: Create symlink for PHP 7
  sudo: yes
  file: src=/usr/bin/php70 dest=/usr/bin/php state=link

- name: Create php.ini defaults
  sudo: yes
  lineinfile: dest=/etc/opt/remi/php70/php.ini regexp='^;date.timezone =' line='date.timezone ={{ php.timezone }}'

- name: Create PHP-FPM service
  sudo: yes
  template: src=php-fpm.service dest=/etc/init.d/php-fpm

- file: path=/etc/init.d/php-fpm state=touch mode="u=rwx,g=rx,o=rx"